### ISSUE TITLE
How should arithmetic opcodes be implemented with regards to the 16th register?

### ISSUE THREAD

**Issue by gagero** [IamMuuo/chip-8#3]
The 16th register acts as the arithmetic carry and no borrow flag, however, I cannot find information on where the extra digit(s) should be stored when doing addition with it set.

**Comment by IamMuuo** [comment]
I think from my notes too there's nothing that says what should be done in that case perhaps its just discarded? not sure what do you suggest

**Comment by gagero** [comment]
If it were discarded, the carry flag wouldn't exist. If it's unset, the extra digit is discarded. Maybe we could store it in both the previous and next words and make the option a compiliation flag?

**Comment by IamMuuo** [comment]
Ok sure. We just have that way we need just to make sure it wouldn't conflict later on as we advance

**Comment by gagero** [comment]
Sorry, I misinterpreted what the carry flag does. This isn't an issue.
